name: GoLicenses

on:
  workflow_call:

concurrency:
  group: golicenses-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golicenses:
    runs-on: [self-hosted, Linux, X64, validator]
    container:
      image: gcr.io/spectro-images-public/golang:1.22-alpine
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          cache: false
          go-version-file: go.mod

      - name: install-golicenses
        run: go install github.com/google/go-licenses@latest

      - name: golicense-scan
        run: |
          go-licenses check --ignore github.com/alibabacloud-go/cr-20160607 ./...
