
name: GoVulnCheck

on:
  workflow_call:

concurrency:
  group: govulncheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  govulncheck:
    runs-on: [self-hosted, Linux, X64, validator]
    container:
      image: gcr.io/spectro-images-public/golang:1.23-alpine
    steps:
      - name: install-govulncheck
        run: GOBIN=/usr/local/bin go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: govulncheck-scan
        run: |
          go version
          govulncheck -mode source ./...
